### PR TITLE
[RDY] Remove the vimproc dependency

### PR DESCRIPTION
**Pull request by Shougo**
It removes the vimproc dependency.
Please test it.

~Current problem:~

~I cannot get the command output from `job_system()` in Vim8.~
~Vim8 job API behavior is hard to understand...~

### CODE REVIEW

**Comment by Shougo** [comment]
Fixed the current problem.
Thank you for @lambdalisue !
The library is very useful for me.

**Comment by Shougo** [comment]
Hm.
vim-vimlint does not support new style `function()`.
We should use vint instead?

**Comment by Shougo** [comment]
I need Windows testers for the branch.
In Linux, Vim8/neovim works for me.

**Comment by AlexMasterov** [comment]
Windows 10 (14986), Vim 8 (p109), vimproc.vim is not installed.

**master branch**
Works fine.

**vimproc branch**
Some operations that use `XCOPY` are slow (20-30s, but is still successfully), while Vim just freezes and "not responding".  An example of such a command:
```cmd
xcopy  /EXCLUDE:C:\Users\Alex\AppData\Local\Temp\VIB2DF7.tmp  "C:\Apps\Vim\vimfiles\dein\repos\github.com\othree\jspc.vim\"* "C:\Apps\Vim\vimfiles\dein\.cache\_vimrc\.dein" /E /H /I /R /Y
```

This command is perform instantly when you manually run from the console (cmd.exe).

**Comment by Shougo** [comment]
Thank you for the testing.
I don't know why xcopy is slow.

**Comment by Shougo** [comment]
I have added sleep.  Please test the latest version.

**Comment by AlexMasterov** [comment]
@Shougo as well.
I changed the command handler to [`system()`](https://github.com/Shougo/dein.vim/blob/77b191cc92b970119e130d1662a9406982a34949/autoload/dein/install.vim#L649) and everything works well and quickly.

**Comment by Shougo** [comment]
I can change it easily.  But I don't want to use `system()` if possible.

**Comment by AlexMasterov** [comment]
It looks like a problem with the `job` implementation. (?)

btw. 
[neomake](https://github.com/neomake/neomake) and [job runner](https://github.com/thinca/vim-quickrun/blob/067984b121176d5dbf7fa60a8fd43d769874302d/autoload/quickrun/runner/job.vim) from [vim-quickrun](https://github.com/thinca/vim-quickrun/tree/master) also does not work properly on Windows. 
Instead, I use [vim-quickrun-job](https://github.com/miyakogi/vim-quickrun-job).

**Comment by Shougo** [comment]
Really?  vim-quickrun-job uses timer feature.  I cannot use it in the case.

**Comment by Shougo** [comment]
@AlexMasterov 

```vim
let result = dein#install#_system([temp])
```

Does not fix the problem?

**Comment by AlexMasterov** [comment]
@Shougo vim-quickrun-job has no problems with the output from the console.

Need to add `/Q` [here](https://github.com/Shougo/dein.vim/blob/b71eee788067ea926a419f2cfd4e97f7d08f024a/autoload/dein/install.vim#L687).

**Comment by Shougo** [comment]
Did.
It fixes the problem?

**Comment by AlexMasterov** [comment]
For [`77b191cc92`](https://github.com/Shougo/dein.vim/tree/77b191cc92b970119e130d1662a9406982a34949) — yes.
I think you understand what the problem was.

**Comment by AlexMasterov** [comment]
After [`77b191cc92`](https://github.com/Shougo/dein.vim/tree/77b191cc92b970119e130d1662a9406982a34949) I got other errors. But `/Q` is really working.
```viml
ile processing function <SNR>28_timer_handler[1]..<SNR>28_install_async[5]..<SNR>28_check_loop[15]..<SNR>28_check_output[52]..<SNR>28_get_updated_log_message[9]..dein#instal
l#_system[10]..13[4]..dein#job#start:
line   24:
E474: Invalid argument
Error detected while processing function <SNR>28_timer_handler[1]..<SNR>28_install_async[5]..<SNR>28_check_loop[15]..<SNR>28_check_output:
line   52:
E171: Missing :endif
Error detected while processing function <SNR>28_timer_handler[1]..<SNR>28_install_async[5]..<SNR>28_check_loop: 
```

**Comment by Shougo** [comment]
@AlexMasterov Please test the latest version.

**Comment by AlexMasterov** [comment]
[`7b4b178`](https://github.com/Shougo/dein.vim/commit/7b4b1781e475344874c486329d0457fcc697fdf6) works fine, thanks. 
And faster than `system()` 👍

**Comment by Shougo** [comment]
Nice!

**Comment by AlexMasterov** [comment]
@Shougo If the output is not used, maybe you should also add `-q` to `rsync`?

[rsync documentation](https://download.samba.org/pub/rsync/rsync.html):
> **-q, --quiet**
> This option decreases the amount of information you are given during the transfer, notably suppressing information messages from the remote server. This option is useful when invoking rsync from cron.

**Comment by Shougo** [comment]
It is nice.  I will do it later.

**Comment by Shougo** [comment]
Force pushed.

**Comment by nhooyr** [comment]
After building `call dein#build(['deoplete-go'])`, I get

```
Error detected while processing function dein#build[1]..dein#install#_build[6]..dein#install#_status:
line    1:
E716: Key not present in Dictionary: status : v:shell_error
E15: Invalid expression: dein#install#_has_job() ? s:job_system.status : v:shell_error
```

**Comment by Shougo** [comment]
Fixed.

**Comment by nhooyr** [comment]
It's very slow again when updating and `has('vim_starting')`. https://asciinema.org/a/4t1ybnh8qo9xddf3yu9uqbhmp

**Comment by nhooyr** [comment]
Here is a comparison between vim-plug, dein, and dein when installing at startup:

vim-plug: https://asciinema.org/a/3rfumjf5yebdiurimph17zvhj
dein: https://asciinema.org/a/21hb8cor76cwtyes2i9ebz6av
startup-dein: https://asciinema.org/a/3c8f9alq064m879ewgmarvcd5

Both dein and vim-plug are very fast, but statup-dein is more than 2x slower than vim-plug and dein!!!

**Comment by Shougo** [comment]
I have implemented asynchronous installation in vim_starting.

**Comment by Shougo** [comment]
I will merge the feature soon.
Please test it more.

**Comment by AlexMasterov** [comment]
@Shougo [`b90b19b`](https://github.com/Shougo/dein.vim/pull/164/commits/b90b19be63384567e86f1a6436b778476f383aa6) works OK.

@nhooyr also try to use: ([--depth ](https://git-scm.com/docs/git-clone#git-clone---depthltdepthgt)1, processes * n)
```viml
let g:dein#types#git#clone_depth = 1
let g:dein#install_max_processes =
    \ exists('$NUMBER_OF_PROCESSORS') ? str2nr($NUMBER_OF_PROCESSORS) * 4 : 8
```

**Comment by Shougo** [comment]
Merged.
Thank you for testing!

**Pull request merged**
