### PR TITLE
Feat: Detect markdown headers in README.md as helptags

### PR DESCRIPTION
**Pull request by KentoOgata**
SSIA

Known issues:

- Cannot open headers that contains 2 byte characters like

```markdown
# 導入方法(例)

## 📦 Requirements
```

- Cannot open headers that contains url (like `[capture](https://github.com/owner/repo)`)
- `'filetype'` option will be set to `help`

### CODE REVIEW

**Comment by Shougo** [comment]
The format is wrong....
Please follow current code.

I will fix it.

**Comment by KentoOgata** [comment]
I'm sorry for submitting bad formatted codes.

Thank you for review.

**Comment by Shougo** [comment]
Fixed the format.

**Comment by KentoOgata** [comment]
Thanks.

**Pull request merged**
