### PR TITLE
Add the option to run a recache manually

### PR DESCRIPTION
**Pull request by hokorobi**
On Windows, I sometimes feel thankful if recaching is done manually.
I would be happy if I can set it up. What do you think?

### CODE REVIEW

**Comment by Shougo** [comment]
> On Windows, I sometimes feel thankful if recaching is done manually.

Please describe the reason more clearly.
And please add the documentation for it.

**Comment by hokorobi** [comment]
> Please describe the reason more clearly.

First, it takes more than 20 seconds to recache in my current environment (Windows) and configuration.

Sometimes recache is executed while editing vimrc. If recache is executed at this time, it seems that recache is also executed at the next start of Vim.
If I run manual recache, it seems that I only need to do this once.

And, hell is waiting for me to edit vimrc with git rebase -i.

> And please add the documentation for it.

OK, I will add.

**Comment by Shougo** [comment]
I think `g:dein#auto_recache` is better.

**Comment by hokorobi** [comment]
Please confirm.

**Comment by hokorobi** [comment]
Thank you.

**Pull request merged**
