### PR TITLE
Align help tags on the right. Put some tags on their own line.

### PR DESCRIPTION
**Pull request by gbcreation**

### CODE REVIEW

**Comment by lambdalisue** [comment]
The lines have 81 characters. These are should be less than or equal to 80.

Additionally, I think aligning tag to the right improve the readability but decrease maintainability.

**Comment by gbcreation** [comment]
@lambdalisue I only modified lines having `*...*` tags, and among them I can't find lines exceeding 80 characters. Could you please tell me what are the lines having 81 characters or more? The only ones I found are lines 341 and 404, but i didn't modify them as they don't have `*...*` tags.

Indeed, the purpose is to improve readability. Once this formatting is done. It should not be change in the future.

**Comment by Shougo** [comment]
@gbcreation Please use vim-helplint.

https://github.com/machakann/vim-vimhelplint

**Comment by gbcreation** [comment]
Thanks for the linter. I fixed my last changes to make them in compliance with it.

**Comment by Shougo** [comment]
LGTM

**Comment by Shougo** [comment]
@gbcreation I will revert this change.  Please use tab characters instead of spaces.
Please see Vim help documents.

**Comment by Shougo** [comment]
It must be *left* align instead of *right*.
I should check it properly though...

**Comment by Shougo** [comment]
I have reverted it by hand :-(

**Pull request merged**
