### PR TITLE
📗 Update README.md

### PR DESCRIPTION
**Pull request by santosned**
As asked by @Shougo, I'd updated README. I also fixed and improved lots of things and chose to sent everything in one commit & PR 🙃

I know it isn't an proper convention-like behavior but I was really short on time. Overall, it's looking like an production-like README file.

## Changes

- Add metadata badges using the widely used [shields.io](https://shields.io/)
- Add details to give the option to hide the table of contents
- Change features section to improve readability.
- Add getting started section to help new users
- Add details to control visibility of config examples
- Add question & answers to answer most relevant questions.
- Add feedback section to help user who want to contribute with the project
- Change TODO section
- Add License info in the footer to follow README conventions

## Notes

It would be nice to have an way to track the versions. Setting it manually, everytime, seems a bit off. What you think?

### CODE REVIEW

**Comment by Shougo** [comment]
Oh...    It is very big..  I need more time to check.

**Comment by Shougo** [comment]
> It would be nice to have an way to track the versions. Setting it manually, everytime, seems a bit off. What you think?

I don't know the better way...

**Comment by santosned** [comment]
> > It would be nice to have an way to track the versions. Setting it manually, everytime, seems a bit off. What you think?
> 
> I don't know the better way...

I think the most viable way would be:

1. To use the versioning system within Github together with Github Actions
This way we could automatically track version for each realese, and run all actions needed.

An example using the release system on Github we can do something like this:

GitHub release (latest by date)

```
![GitHub release (latest by date)](https://img.shields.io/github/v/release/microsoft/vscode)
```

Which would automatically get the latest stable release.

You can see more about [here](https://docs.github.com/en/repositories/releasing-projects-on-github/managing-releases-in-a-repository).

**Comment by Shougo** [comment]
OK.  I will add release.

**Comment by Shougo** [comment]
I have released 3.0.

**Pull request merged**
